services:
  db:
    image: postgres:alpine
    user: postgres
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres", "-U", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    secrets:
      - postgres_password

  api:
    build:
      context: .
    environment:
      - DB_URI=postgresql://postgres:__pass__@db:5432/postgres?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - postgres_password

secrets:
  postgres_password:
    file: ./postgres_password.txt
